/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zmkxsesiefrefwhjkhhk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpta3hzZXNpZWZyZWZ3aGpraGhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxODE1MTksImV4cCI6MjA4NTc1NzUxOX0.cra8Gpjd4m-Le0Riu5UB7-Sk6v13_rLdK4Jaz3PjTjU"